PUD-94: Add nomsNumber into generate-revocation-order api
ministryofjustice/manage-recalls-ui pull request #44
Opened 2021-07-05 15:35 UTC by NataliaOsk

2021-07-05 15:36 UTC, philsegal requested changes
Remove package-lock.json changes

2021-07-05 15:41 UTC, philsegal submitted a review, later dismissed

2021-07-05 20:13 UTC, jonnywyatt commented on server/views/pages/offenderProfile.njk
> +                <form action="/generate-revocation-order" method="post">
This will cause a page reload, plus the download needs to be triggered?

2021-07-09 13:33 UTC, jonnywyatt submitted a review, later dismissed

2021-07-09 13:33 UTC, jonnywyatt commented on README.md
> +docker compose -f docker-compose-test.yml up
Was this not working before?

2021-07-09 13:56 UTC, jonnywyatt approved these changes

2021-07-09 14:17 UTC, merged